go_library(
    name = "display",
    srcs = [
        "editor.go",
        "search.go",
        "screen_region.go",
    ],
    visibility = ["//ejacks/editor"],
    deps = [
        "//third_party/go:tcell",
    ],
)
